### ISSUE TITLE
Inconsistency in first-view behavior

### ISSUE THREAD

**Issue by pinin4fjords** [ebi-gene-expression-group/atlas-web-single-cell#135]
If I go here:

https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-HCAD-9/results/anatomogram

... the first view is 'pre-zoomed', i.e. clicking the insert zooms out. 

If I go here:

https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-ENAD-27/results/anatomogram

The first view is the 'top'.

I realise this may be down to some ontology-related reason, but I find the behaviour confusing.

**Comment by alfonsomunozpomer** [comment]
This bug is actually what’s causing https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/136.

**Comment by alfonsomunozpomer** [comment]
https://www.pivotaltracker.com/story/show/176997111

**Comment by pcm32** [comment]
Same here please @pinin4fjords, could you check if this looks good on wwwdev? Thanks

**Comment by pinin4fjords** [comment]
This one looking good too
