### ISSUE TITLE
Going up one level and returning produces a different set of cell types

### ISSUE THREAD

**Issue by pinin4fjords** [ebi-gene-expression-group/atlas-web-single-cell#136]
Step to reproduce:

1. Go to https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-HCAD-9/results/anatomogram
2. Observe single cell type in heatmap
3. Click insert to zoom out
4. Box to zoom back
5. Observe two cell types in heat map, one of which is not evident in zoomed view.

**Comment by alfonsomunozpomer** [comment]
https://www.pivotaltracker.com/story/show/176997111

**Comment by pcm32** [comment]
@pinin4fjords could you please check if this now works as you expect on wwwdev? Thanks

**Comment by pinin4fjords** [comment]
Yep, looking good

**Comment by ngeorgeebi** [comment]
I've checked too - following @pinin4fjords helpful to do list - and works for me too 👍
