### ISSUE TITLE
Cell types not highlighted/ clickable when visible in heatmap

### ISSUE THREAD

**Issue by pinin4fjords** [ebi-gene-expression-group/atlas-web-single-cell#137]
Steps to reproduce:

- Go to https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-MTAB-5061/results/anatomogram
- Click to zoomed view (noting missing highlight for Islet of Langerhans as reported in https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/128). 
- Note that B-cells are present in heatmap but not highlighted/clickable in anatomogram.

**Comment by alfonsomunozpomer** [comment]
Again, due to missing ontology expansion. This is fine in https://www-test.ebi.ac.uk/gxa/sc/experiments/E-MTAB-5061/results/anatomogram.
