### ISSUE TITLE
Download from experiments table not working

### ISSUE THREAD

**Issue by anjaf** [ebi-gene-expression-group/atlas-web-single-cell#153]
The bundled download from the browse experiments table stopped working (currently on wwwdev and prod). 

Tested in Firefox 84 (Mac) and Chrome 88 (Mac)

How to replicate:
Go to https://www.ebi.ac.uk/gxa/sc/experiments
Select experiment(s)
Click "Download 1 entry"
... nothing happens.

**Comment by alfonsomunozpomer** [comment]
https://www.pivotaltracker.com/story/show/176997070

**Comment by pcm32** [comment]
Something happens now: I get selection prompt for files and then a new blank screen making a request for a zip file:

https://www.ebi.ac.uk/gxa/sc/experiments/download/zip?accession=E-GEOD-158761&fileType=quantification-raw&fileType=normalised&fileType=experiment-design

but I get no downloads (at least not within ~5 minutes)...

**Comment by pcm32** [comment]
@haideriqbal can you check what is going on. I tried this on mac / Chrome.

**Comment by pcm32** [comment]
Also, I'm clicking for downloads on wwwdev, but download link where I'm taken points to www, which cannot be good.

**Comment by upendrakumbham** [comment]
Tested master branch SCXA application. The `download` link is working fine in the master branch.

**Comment by pcm32** [comment]
It might be that the failure only comes on wwwdev given the unexpected redirection to www after selecting what to download.

**Comment by upendrakumbham** [comment]
Maybe your correct @pcm32, something is going wrong on wwwdev, the `Download` link is working fine in the release branch as well in my local machine.

**Comment by alfonsomunozpomer** [comment]
deec4edc744a8146f7ab9fb4a4bb44f1e79b7e0e fixes this problem. The download link was hard-coded to `http://www.ebi.ac.uk/gxa/sc` which won’t work until we deploy to production.

**Comment by upendrakumbham** [comment]
`Download ` link is working fine on` wwwdev `

**Comment by pcm32** [comment]
Great thanks!

**Comment by ngeorgeebi** [comment]
I've just tested this, with the 'Download 1 entry' as @anjaf described and nothing happens for me :(

**Comment by ngeorgeebi** [comment]
@pcm32 potentially reopen? - other testers needed. I did it on dev

**Comment by pcm32** [comment]
I have just re-tried, it worked for me.... ah, I see now that you changed your comment. All good then.
