### ISSUE TITLE
The content of the feedback pop-up misaligned on Chrome, MS Edge and Safari

### ISSUE THREAD

**Issue by datasome** [ebi-gene-expression-group/atlas-web-single-cell#16]
E.g on https://www.ebi.ac.uk/gxa/sc/search?species=&q=aspm, the feedback pop-up misaligned in Chrome, Safari and Microsoft Edge (but fine in Firefox) - see: https://www.ebi.ac.uk/~rpetry/testing/scgxa/scgxa_issues1.png

**Comment by alfonsomunozpomer** [comment]
[This has been fixed](https://www.pivotaltracker.com/story/show/164694915). Please check [the same link in the production server](https://wwwdev.ebi.ac.uk/gxa/sc/search?species=&q=aspm).
