### ISSUE TITLE
Microsoft Edge - on experiments page, only every other experiment title is underlined.

### ISSUE THREAD

**Issue by datasome** [ebi-gene-expression-group/atlas-web-single-cell#17]
A minor point - on https://www.ebi.ac.uk/gxa/sc/experiments, all experiment titles are links but (unlike in other browsers) in Microsoft Edge only every other one has a dotted underline - see: https://www.ebi.ac.uk/~rpetry/testing/gxa/gxa_issues23.png

**Comment by alfonsomunozpomer** [comment]
This is now fixed in [the new experiments table](https://github.com/ebi-gene-expression-group/atlas-experiment-table). Please take a look in the production environment.
