### ISSUE TITLE
Experiment page is not landing by default on inferred cell type ontology labels as it should

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/atlas-web-single-cell#181]
This is a feature that was introduced in the last release, on landing to an experiment the colouring should be based on the Inferred cell type ontology labels if available. Currently is preferring a clustering value. Clustering colouring should always be at the end of the priority list for coloring. This applies to both tSNE and UMAP.

See correct behaviour in www, for instance for https://www.ebi.ac.uk/gxa/sc/experiments/E-MTAB-9067/results/tsne

**Comment by haideriqbal** [comment]
Closing this issue as it has been fixed here https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/186
