### ISSUE TITLE
Anatomogram for E-MTAB-9067 doesn't show data when clicking on the next level of detail

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/atlas-web-single-cell#183]
The anatomogram here at the first level seems to work well

https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-MTAB-9067/results/anatomogram?colourBy=inferred+cell+type+-+authors+labels

However, on clicking on the next level of detail (blue rectangle), we get:

![image](https://user-images.githubusercontent.com/368478/126837253-8ef3f93b-5778-4051-ba4e-7a965779d552.png)

**Comment by pcm32** [comment]
Maybe given the joint nature of liver and bone marrow, and the fact that this is developmental, means that we should not show an anatomogram in this case @ebi-gene-expression-group/curation ?

**Comment by sfexova** [comment]
this experiment shouldn't have an anatomogram, it's foetal sample (not adult tissue)

**Comment by ngbush** [comment]
Not sure this is the best place for this, but this one also has an anatomagram but it is foetal tissue: https://www.ebi.ac.uk/gxa/sc/experiments/E-MTAB-7407/results/anatomogram

**Comment by pcm32** [comment]
Should we black list them both then?

**Comment by pcm32** [comment]
@haideriqbal since you worked on this before, could you please black-list from anatomograms E-MTAB-7407 and E-MTAB-9067? This pivotal history contains PR links on how this was done last time: https://www.pivotaltracker.com/n/projects/611105/stories/176762368

**Comment by haideriqbal** [comment]
@pcm32 sure!

**Comment by pcm32** [comment]
This is no longer showing anatomograms at https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-MTAB-9067/results/tsne, and the same for https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-MTAB-7407/results/tsne, so this is resolved in my view. Thanks everyone and specially @haideriqbal .
