### ISSUE TITLE
Colour by metadata broken on dev

### ISSUE THREAD

**Issue by sfexova** [ebi-gene-expression-group/atlas-web-single-cell#187]
Hi guys! The colour by metadata doesn't work on dev - none of the metadata categories get displayed in the charts (either t-SNE or UMAP), it just says 'not defined' for all. I suspect it may be the addition of the UMAP chart that somehow broke this because I was checking recently added experiments to see if any needed batch correction before the UMAP was implemented on dev and all looked fine then. 
<img width="1035" alt="Screen Shot 2021-08-02 at 11 29 45" src="https://user-images.githubusercontent.com/30924848/127847702-05463e0e-e574-4693-b150-d80b360ec397.png">

**Comment by pcm32** [comment]
Thanks @sfexova, this reported in #180, so I will close it to avoid duplication.
