### ISSUE TITLE
"scxa-analytics-v6" Solr collection test result and errors

### ISSUE THREAD

**Issue by upendrakumbham** [ebi-gene-expression-group/atlas-web-single-cell#193]
Issues I have noticed so far:

1. Clicked on Browse experiments: Got a list of experiments
2.  Clicked on 'Transcriptomic and clonal characterization of T cells in the human central nervous system'. Got results tab with 2 buttons "Cell plots" and "Marker-Genes".
3. Under the cluster plots section, point the mouse cursor on dots to see the metadata of that dot. It calls  this endpoint 
`"https://wwwdev.ebi.ac.uk/gxa/sc/json/experiment/E-HCAD-30/cell/SAMN15959135-GACGTTATCATC/metadata"`
This endpoint contact Solr to fetch metadata of that cell-id. This endpoint giving a `400` error for the majority of the dots.
When I hit metadata endpoint on the browse: I could see this error:

`{"error":"class java.lang.String cannot be cast to class java.util.ArrayList (java.lang.String and java.util.ArrayList are in module java.base of loader \u0027bootstrap\u0027)"}`

Solr result is unable to parse by the java code.
Endpoint:
`https://wwwdev.ebi.ac.uk/gxa/sc/json/experiment/E-HCAD-30/cell/SAMN15959138-TGTCCCACAAGA/metadata`
`Status: 200`
`[{"displayName":"Protocol","value":"total nuclei"},{"displayName":"Sampling site","value":"middle temporal gyrus"},{"displayName":"Sex","value":"male"},{"displayName":"Individual","value":"brain_donor_2"},{"displayName":"Age","value":"41 year"}]`

Clicked on 'Marker-Gene':`
1. Click on gene symbol: Error: Got this:  /gxa/sc/json/search?q=MT2A&species=homo+sapiens => 500

A few Experiments got this error: https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-MTAB-8530/results
```
Error: 400
We are sorry - an unexpected error occurred. If it persists, please get in touch with us through the EBI Support & feedback form.

```

**Comment by alfonsomunozpomer** [comment]
This is now fixed.
