### ISSUE TITLE
Numbers appearing after each value in tooltip box in metadata search wheel

### ISSUE THREAD

**Issue by sfexova** [ebi-gene-expression-group/atlas-web-single-cell#202]
In every section of the metadata search wheel, when you hover over it and the label box appears it contains a colon and a number (1 in all the examples I tried). This is not just for the cell types but also the other fields like the organism (e.g. when hovering over the 'Homo sapiens' section of the wheel a label 'Homo sapiens: 1" appear). Can we lose these numbers from the label boxes please?
![Screen Shot 2021-10-13 at 13 17 21](https://user-images.githubusercontent.com/30924848/137131540-150204af-6554-4908-b5b8-43983ec8e292.png)

**Comment by alfonsomunozpomer** [comment]
This is now fixed.
