### ISSUE TITLE
'Not available' blots out more useful metadata categories

### ISSUE THREAD

**Issue by pinin4fjords** [ebi-gene-expression-group/atlas-web-single-cell#207]
Problem: Unlabelled cells in large datatsets can blot out labelled ones, presumably due to plot order, as they do in the FCA dataset: https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-MTAB-10519/results/tsne?plotOption=20&plotType=tsne&colourBy=inferred+cell+type+-+authors+labels.

Could the plot order be tweaked to address this?

**Comment by alfonsomunozpomer** [comment]
Fixed by https://github.com/ebi-gene-expression-group/atlas-components/pull/108.
