### ISSUE TITLE
Download -> Print chart produces blank page for expression tsne

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/atlas-web-single-cell#21]
When looking to the expression tsne (the one to your right), and choosing Download -> Print chart, a blank document is generated. I saw this behaviour here:

https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-ENAD-13/results/tsne?geneId=ENSMUSG00000041301
https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-ENAD-17/

with or without the gene search. I have reproduced this error 3 times, macOS with Chrome.

**Comment by pcm32** [comment]
![image](https://user-images.githubusercontent.com/368478/60098001-823f3580-974c-11e9-914e-481f0b3e3ddc.png)

**Comment by pcm32** [comment]
Web browser also turns into this:
![image](https://user-images.githubusercontent.com/368478/60098068-a9960280-974c-11e9-9300-1fb334bf2c0d.png)

**Comment by pcm32** [comment]
This is on Chrome Version 75.0.3770.90 (Official Build) (64-bit) for macOS (High Sierra). On Firefox it works well.

**Comment by alfonsomunozpomer** [comment]
@lingyun1010 Can you replicate this bug on your end? I don’t have any Mac nearby to check.

**Comment by alfonsomunozpomer** [comment]
We haven’t been able to determine if this is a problem in a specific browser, OS, Highcharts or a combination of some of those elements. [We have removed the Print option](https://www.pivotaltracker.com/story/show/166902135) which also has the nice side-effect of the *Download* button being for downloads only. Any user can then print an image or a PDF if they wish. :smile:
