### ISSUE TITLE
Metadata pop-up unstable on large datasets

### ISSUE THREAD

**Issue by pinin4fjords** [ebi-gene-expression-group/atlas-web-single-cell#23]
Steps to reproduce:

- Visit a large dataset e.g. https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-ENAD-15/results/tsne
- Mouse over clusters plot. Once metadata eventually loads, note that the popup content is not stable, and circulates through that of nearby points. 

Tested on:

- OSX Chrome 74.0.3729.169 (Official Build) (64-bit)
- MacBook Pro (15-inch, 2017), 2.9 GHz Intel Core i7, 16 GB RAM

**Comment by pinin4fjords** [comment]
Encountered this again today when trying to browse Tabula Muris:

- Visit https://www.ebi.ac.uk/gxa/sc/experiments/E-ENAD-15/results
- Use the legend to hide e.g. Basal cells
- Observe that there is a small number of cells in the space vacated, mouse over one
- Observe the slightly mad cycling of metadata

**Comment by alfonsomunozpomer** [comment]
Unfortunately this is something that escapes a bit our control, since we rely on Highcharts to show tooltips of data points. We’ll open an issue in their repo and hope for the best.

**Comment by alfonsomunozpomer** [comment]
I’m closing this one since it seems that it was fixed at some point with recent versions of Highcharts. Feel free to re-open if it happens again, of course.
