### ISSUE TITLE
Experiments page showing wrong number of datasets

### ISSUE THREAD

**Issue by pinin4fjords** [ebi-gene-expression-group/atlas-web-single-cell#24]
https://wwwdev.ebi.ac.uk/gxa/sc/experiments is currently showing 96 datasets, when it should be 98.

**Comment by alfonsomunozpomer** [comment]
This was happening because of a very aggressive caching strategy, so that new experiments weren’t shown in the current session and required an app restart. [This has now been solved](https://www.pivotaltracker.com/story/show/166930142).
