### ISSUE TITLE
Empty colorscale after PDF download of heatmap [cell type wheel]

### ISSUE THREAD

**Issue by pmb59** [ebi-gene-expression-group/atlas-web-single-cell#247]
However, the PNG download  shows the blue colorscale correctly.
I tried this example https://wwwdev.ebi.ac.uk/gxa/sc/search/metadata/DIABETES%20MELLITUS%20TYPE%2002

**Comment by pcm32** [comment]
We have isolated this to be an issue from mac preview, neither adobe acrobat nor direct Chrome rendering have the issue. So I think that we will leave it for now. Thanks for reporting!
