### ISSUE TITLE
Timeouts on first load of large datasets

### ISSUE THREAD

**Issue by pinin4fjords** [ebi-gene-expression-group/atlas-web-single-cell#25]
The first time loading large datasets produces an error (presumably due to unfilled caches). The below was produced for https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-MTAB-7320/results.

![Screen Shot 2019-06-25 at 13 41 06](https://user-images.githubusercontent.com/5775915/60100183-17442d80-9751-11e9-8cac-5c4b3ed73fc0.png)

**Comment by alfonsomunozpomer** [comment]
Fixed by capping the experiment design table to the first 1,000 rows.
