### ISSUE TITLE
make exp accessions in cell type wheel marker table into hyperlinks

### ISSUE THREAD

**Issue by sfexova** [ebi-gene-expression-group/atlas-web-single-cell#250]
not sure but I think we were planning to have this functionality (?) - in any case, I think it would be good if users could jump from the cell type wheel marker gene table directly to the relevant experiments, can we add the hyperlinks here?
<img width="1618" alt="Screenshot 2022-06-06 at 20 46 57" src="https://user-images.githubusercontent.com/30924848/172236435-00c6133f-a4c2-49b9-970a-dfe31b55cb3b.png">

**Comment by pcm32** [comment]
This is covered by one existing story, so will be done.

**Comment by alfonsomunozpomer** [comment]
Fixed by https://github.com/ebi-gene-expression-group/atlas-components/pull/115.
