### ISSUE TITLE
[cell type wheel] heatmap for human cell type shows results from mice

### ISSUE THREAD

**Issue by sfexova** [ebi-gene-expression-group/atlas-web-single-cell#254]
E.g. searching for 'cancer' https://wwwdev.ebi.ac.uk/gxa/sc/search/metadata/cancer gets results from 3 different organisms (mouse, human, zebrafish)  - when I selected human>caecum>goblet cell, however, I'm getting results from E-ENAD-13 and E-ENAD-14, which are both mouse experiments.

**Comment by alfonsomunozpomer** [comment]
Fixed by https://github.com/ebi-gene-expression-group/atlas-components/pull/111.
