### ISSUE TITLE
Versions for Ensembl Genomes, WormBase and EFO not showing up on home page

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/atlas-web-single-cell#26]
![image](https://user-images.githubusercontent.com/368478/60165653-91c78880-97f7-11e9-87a9-2916089e4a93.png)

https://wwwdev.ebi.ac.uk/gxa/sc/home

**Comment by alfonsomunozpomer** [comment]
Fixed in 9a860f6a8da996b9d77a4495f0e53fa6244399a4.
