### ISSUE TITLE
Too much recursion error when searching for Gallus gallus metadata

### ISSUE THREAD

**Issue by alfonsomunozpomer** [ebi-gene-expression-group/atlas-web-single-cell#278]
https://www.ebi.ac.uk/gxa/sc/search/metadata/Gallus%20gallus

The error happens whenever you search for a species in the metadata search box.
For example: liver.
Species are not passes to the controller.

**Comment by upendrakumbham** [comment]
Created PR for this issue, hence closing the issue.
