### ISSUE TITLE
Incomplete visualisation when coming from Gene search

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/atlas-web-single-cell#29]
When clicking in one of the example searches (CFTR) and then clicking on the link for E-ENAD-15 result for marker genes at a defined k value, it produces an incomplete visualisation.

![image](https://user-images.githubusercontent.com/368478/60250058-d7e71f80-98bd-11e9-975f-629ed62647c0.png)

Also the download button went back to HTML text.

https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-ENAD-15/results/tsne?geneId=ENSMUSG00000041301&k=35&clusterId=%5B8%5D

**Comment by pcm32** [comment]
Maybe this is sort of similar to the expected functionality, where only the relevant cluster is shown, but in this case is showing cluster 1 and not cluster 8, which is the one where the gene is a marker gene.

**Comment by pcm32** [comment]
It is weird... the hover over on the only available cluster shows cluster 1, but if you turn on/off cluster 1 in the names below, another cluster is showing up.... so according to the names switches below, that is not cluster 1 but cluster 8.

**Comment by pcm32** [comment]
Ok, the cluster shown to the right is cluster 1, however it should be showing cluster 8. When you click on cluster 1 or cluster 8, things change on the left tsne, clicking on any of the other clusters nothing happens.

**Comment by pcm32** [comment]
Also, dots in they key are very small and don't really allow to see the color.

**Comment by lingyun1010** [comment]
The incomplete visualization is temporarily fixed by ignoring highlighted cluster marked in Gene Search results, i.e. without dimmed grey tSNE points.

**Comment by alfonsomunozpomer** [comment]
[Fixed](https://github.com/ebi-gene-expression-group/scxa-experiment-page-tsne-plot-view/commit/9396d6adc97efad230cfcd0ac3f417715260260a).
