### ISSUE TITLE
Cluster dots in the key are very small when there are many clusters in the tSNE

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/atlas-web-single-cell#33]
With experiments that have lots of clusters, the dot before the cluster name is very small and the colour of the cluster cannot be easily appreciated:

![image](https://user-images.githubusercontent.com/368478/60323452-0aeee900-997a-11e9-826a-24b9041f2eb7.png)

https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-MTAB-6946/results/tsne

macOS / Chrome

**Comment by alfonsomunozpomer** [comment]
[Fixed](https://github.com/ebi-gene-expression-group/scxa-experiment-page-tsne-plot-view/pull/28).

![image](https://user-images.githubusercontent.com/4425744/60674818-e52e7c00-9e72-11e9-8af2-7fb7dcca4ce0.png)
