### ISSUE TITLE
Metadata available for cell identifier in Solr not displayed in tSNE

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/atlas-web-single-cell#34]
For cell id HP_15085_01T2D__8dcult_26031 of experiment E-GEOD-83139, the metadata is not displayed even though the data is in solr 

https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-GEOD-83139/results?colourBy=metadata&metadata=growth_condition

![image](https://user-images.githubusercontent.com/368478/60346281-bd42a280-99b2-11e9-8101-7b2fb035ac13.png)

http://wp-np2-86:8983/solr/scxa-analytics-v3/select?q=cell_id:%22HP_15085_01T2D__8dcult_26031%22

**Comment by pcm32** [comment]
That happens for a number of other identifiers, although not all of them, in the dataset.

**Comment by alfonsomunozpomer** [comment]
I can’t really reproduce this bug. Very probably it’s related to https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/22.
