### ISSUE TITLE
Showing gray color plot expression when we click on specific experiment for the first time page load

### ISSUE THREAD

**Issue by upendrakumbham** [ebi-gene-expression-group/atlas-web-single-cell#361]
In the SCXA a few experiments don't have metadata. Those experiments have given empty colour plot expressions when clicking on the experiment.

`Ex: https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-GEOD-99058/results/tsne`

Here is the screenshot:

![Image](https://github.com/ebi-gene-expression-group/atlas-web-single-cell/assets/15771356/caf8e515-af63-414c-9f37-5268a637d442)

Change the K value to something and return to the same k value that is `23`, then you will see a colour plot.

-  We are getting an empty colour plot for the metadata available experiments too.

![Image](https://github.com/ebi-gene-expression-group/atlas-web-single-cell/assets/15771356/deb38161-d111-4b62-a95b-7db034c82cbd)

Empty colour plot  screen shot:

![Image](https://github.com/ebi-gene-expression-group/atlas-web-single-cell/assets/15771356/cf8b280a-3df1-45a7-8da9-6ee1113ff620)

**Comment by ke4** [comment]
@upendrakumbham thanks for adding this ticket to the backlog

**Comment by ke4** [comment]
We hope that this issue: https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/363 will fix this one, as well.

**Comment by ke4** [comment]
This has been fixed by previous `t-SNE` related tickets.

- #364 
- #370
