### ISSUE TITLE
Experiment page: preferred K doesn't always have marker genes

### ISSUE THREAD

**Issue by monicajianu** [ebi-gene-expression-group/atlas-web-single-cell#38]
The default K passed to the marker genes heatmap is the preferred K from the t-SNE plot. However, for some experiments (such as [E-MTAB-6946](https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-MTAB-6946/results/tsne)) when you click on the marker genes tab you get no results. 

Ideally, there should be an additional check to see if the preferred K has marker genes, if not, select the next item in the list of available Ks.

**Comment by alfonsomunozpomer** [comment]
Dear Single Cell Expression Atlas user, thank you sou much for your concern and continued support! :wink:

TBH, I’m not really sure if that’s a desired behaviour: since the preferred *k* is a curated value and in principle having the selected *k* changed by (IMO) not a very apparent reason may break user’s expectation.

I’ll bring it up in the next team meeting.

**Comment by monicajianu** [comment]
I just meant change the default selected k for the marker genes heatmap, not the preferred k for the entire experiment. As it is now, when you click on the marker genes, you end up in an illegal state where something that is normally greyed out in the dropdown is selected.

**Comment by alfonsomunozpomer** [comment]
Yes, I understand what you meant. It’s just that switching to a different *k* when you toggle the heatmap (from the default *k* in the t-SNE plot) may mislead users to thinking they’re seeing the same clustering option and wonder why there are more/fewer clusters than they expect (or why it was changed in the first place). I’m not really sure that’s what we want. In this way we keep consistency across visualisations although we don’t show the full glory of the heatmap that our beloved developer (albeit now gone for greener pastures) so painstakingly worked on.

I think there are tradeoffs in each behaviour. Ideally, if we change the k value, I’d like to be very explicit about it: informing the user somehow that the *k* has been changed in the heatmap and why.

**Comment by pcm32** [comment]
I think we could do something better at the prod side for this. We currently prefer the k value that is produced by the scanpy resolution closer to 1. We could add a condition that it should prefer the closest one to Res=1 that has marker genes. What do you think @pinin4fjords ? Maybe Ni or Carlos might have some useful comments in this as well.

**Comment by pcm32** [comment]
Love your attachment to your creation @monicajianu ;-)

**Comment by alfonsomunozpomer** [comment]
Closing after eight months of inactivity.

**Comment by monicajianu** [comment]
😢 😁
