### ISSUE TITLE
📦 atlas-experiment-table  💬  Add icon for Anndata experiments in the experiments list page

### ISSUE THREAD

**Issue by ke4** [ebi-gene-expression-group/atlas-web-single-cell#392]
We have to add the Anndata icon to the title column if it is an Anndata experiment.

On our last Team meeting we decided to replace the Avenger-styled icon to a simple `A` with a capital A in red-ish background.
The tooltip text should be: `Experiment with annotated data analysed by an external source.`
In another ticket we are also going to modify it and add a link to a help page that giving more details on Anndata to the user.

**Comment by lingyun1010** [comment]
Remaining to do: Integrate the front-end component to single-cell web application
