### ISSUE TITLE
Modify the title session of an Anndata experiment

### ISSUE THREAD

**Issue by ke4** [ebi-gene-expression-group/atlas-web-single-cell#393]
If the experiment is an Anndata experiment, then we have to differentiate it from other experiments.
In the title session we have to do the following changes:
- have a different shade in the background (specify the colour with @Silvie)
- add the Anndata specific icon to the right side of the title session

![Image](https://github.com/ebi-gene-expression-group/atlas-web-single-cell/assets/2183410/66c673ff-5a22-44d5-ab61-6f28f4772f55)

**Comment by sfexova** [comment]
Hi, can we try light orange maybe?
