### ISSUE TITLE
Clicking on cell types on the wheel is not working after we searched for a species

### ISSUE THREAD

**Issue by ke4** [ebi-gene-expression-group/atlas-web-single-cell#432]

**Comment by lingyun1010** [comment]
Given the search term is `Mus musculus`, https://wwwdev.ebi.ac.uk/gxa/sc/search/metadata/Mus%20musculus.

The cell type wheel is not homogeneous, i.e., one node has four levels and the others only have three levels.

In our implementation senario, we always consider to trigger a gene expression search on the level 4. 
```
          point: {
            events: {
              click: function () {
                if (this.node.level === 4) {
                  const species = _.split(this.id, `#`, 1)
                  props.onCellTypeWheelClick(this.name, species[0], this.experimentAccessions)
                }
              }
            }
          },
```

So, in this case, if the node `lymphocyte` is clicked, it requested gene expression from endpoints as usual, but the others are not. 

It is a bit hard to say now, we need to confirm with curators to check what to do,
1. Species metadata search is allowed?
2. 4 levels and uneven levels in the cell type wheel is allowed?
3. Gene expression search from level 3 in the species-centred wheel is enabled?

**Comment by lingyun1010** [comment]
Based on the team meeting discussion, we have the following conclusions:
1. Species search is allowed.
2. The cell type wheel should be homogeneous and there is a bug data in this example search,  https://wwwdev.ebi.ac.uk/gxa/sc/search/metadata/Mus%20musculus. where we have a four level, from `Homo sapiens` section, which should not be included in the `Mus musculus` search
3. Level 3 should be the gene expression search level for species-centred wheel.
