### ISSUE TITLE
Cannot switch between k values from marker genes plot in some experiments

### ISSUE THREAD

**Issue by pinin4fjords** [ebi-gene-expression-group/atlas-web-single-cell#71]
Issue per title.

I suspect this the case where the default k value has no markers. e.g.:

https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-MTAB-6946/results/marker-genes?colourBy=clusters&k=68&markerGeneK=68

The menu is greyed out like:

![Screenshot 2019-12-13 at 13 21 39](https://user-images.githubusercontent.com/5775915/70804573-bc5dcb80-1dae-11ea-9f37-d3dc7ae97807.png)

**Comment by alfonsomunozpomer** [comment]
This has ben fixed. In fact it needn’t be fixed, it was a caching issue.
