### ISSUE TITLE
Experiment links on HCA landing page not working

### ISSUE THREAD

**Issue by anjaf** [ebi-gene-expression-group/atlas-web-single-cell#75]
A user reported that all links leading out to HCA experiments from the HCA landing page (https://www.ebi.ac.uk/gxa/sc/hca-landing-page.html) are broken. Instead of www.ebi.ac.uk they point to a GitHub domain. 
An example: 
Clicking "Mouse cells - Small intestinal epithelium" leads to https://ebi-gene-expression-group.github.io/gxa/sc/experiments/E-EHCA-2

**Comment by alfonsomunozpomer** [comment]
This has now been fixed. Thanks for the feedback!
