### ISSUE TITLE
Inferred cell type cannot be removed from filter once added

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/atlas-web-single-cell#82]
After searching for a gene symbol (CFTR), the application of the filter for cell types on the left cannot be reversed by clicking on the x next to the added cell type (lower left corner of the screenshot):

![image](https://user-images.githubusercontent.com/368478/76003040-6dcc5300-5eff-11ea-8727-128c75aa301a.png)

So on clicking the red cross, it doesn't go away.

`/gxa/sc/search?species=&symbol=CFTR`

macOS / Chrome

**Comment by pcm32** [comment]
To add to this, I can mention that the error happens when you only have a single value in the field; when you have two fields, clicking on the red x for one of them does delete it as expected. So this would be a nice to have fix, but I don't think that this amounts to a release blocker if not fixed.

**Comment by alfonsomunozpomer** [comment]
Fixed in the linked PR.
