### ISSUE TITLE
Points in t-SNE legend too small

### ISSUE THREAD

**Issue by pinin4fjords** [ebi-gene-expression-group/atlas-web-single-cell#87]
Can't distinguish color in legend because the points are too small:

<img width="499" alt="Screenshot 2020-03-16 at 10 26 32" src="https://user-images.githubusercontent.com/5775915/76747275-ce198b00-6770-11ea-9d22-fd9ccd67aef8.png">

(from https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-HCAD-4/results/tsne?colourBy=metadata&metadata=individual)

Chrome 79.0.3945.117 on OSX.

**Comment by alfonsomunozpomer** [comment]
We’ve made the dots a bit bigger in large plots. If this is still an issue, feel free to reopen it.
